export const Users = [
  {
    id:1,
    profilePicture: "f1.jpg",
    username: "Loe Man",
  },
  {
    id:2,
    profilePicture: "f2.jpg",
    username: "Kloe Adaze",
  },
  {
    id:3,
    profilePicture: "f3.jpg",
    username: "Alex Dum",
  },
  {
    id:4,
    profilePicture: "f4.jpg",
    username: "Dora Kuro",
  },
  {
    id:5,
    profilePicture: "f5.jpeg",
    username: "Tom Bola",
  },
  {
    id:6,
    profilePicture: "f6.jpg",
    username: "Kyle Ada",
  },
  {
    id:7,
    profilePicture: "f7.jpg",
    username: "Ebi Kuro",
  },
  {
    id:8,
    profilePicture: "f8.jpg",
    username: "Bile Igo",
  },
  {
    id:9,
    profilePicture: "f9.jpg",
    username: "Tari Ben",
  },
  {
    id:10,
    profilePicture: "f10.jpg",
    username: "Dike Olu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "f1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "f2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "f3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "f4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "f5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "f6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "f7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "f8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "f9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "f10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
